spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: p@ssw0rd
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata